IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'TaskDB')
BEGIN
    CREATE DATABASE TaskDB;
END
GO

USE TaskDB;
GO

IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_NAME = 'Tasks' AND TABLE_TYPE = 'BASE TABLE'
)
BEGIN
    CREATE TABLE Tasks (
        Id INT PRIMARY KEY IDENTITY(1,1),
        Title NVARCHAR(255) NOT NULL,
        Description NVARCHAR(MAX),
        IsCompleted BIT NOT NULL DEFAULT 0,
        CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
    );
END
GO
